/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c8c6c5",
        "secondary-container": "#464747",
        "on-tertiary-fixed": "#1b1c1c",
        "primary": "#ffffff",
        "tertiary-container": "#e5e2e1",
        "on-primary-fixed": "#1a1c1b",
        "surface-dim": "#131313",
        "secondary": "#c7c6c6",
        "outline": "#8e928f",
        "surface-container-lowest": "#0e0e0e",
        "primary-fixed": "#e2e3e1",
        "on-secondary-container": "#b5b5b5",
        "surface-container-high": "#2a2a2a",
        "surface-bright": "#3a3939",
        "inverse-primary": "#5d5f5d",
        "on-tertiary-container": "#656464",
        "surface-container-highest": "#353534",
        "surface-tint": "#c6c7c5",
        "tertiary-fixed": "#e5e2e1",
        "on-tertiary-fixed-variant": "#474746",
        "on-primary-fixed-variant": "#454746",
        "primary-container": "#e2e3e1",
        "error": "#ffb4ab",
        "on-surface-variant": "#c4c7c5",
        "surface": "#131313",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-variant": "#353534",
        "secondary-fixed-dim": "#c7c6c6",
        "inverse-surface": "#e5e2e1",
        "on-secondary-fixed-variant": "#464747",
        "inverse-on-surface": "#313030",
        "tertiary": "#ffffff",
        "on-surface": "#e5e2e1",
        "on-error": "#690005",
        "primary-fixed-dim": "#c6c7c5",
        "on-background": "#e5e2e1",
        "surface-container": "#201f1f",
        "secondary-fixed": "#e3e2e2",
        "on-tertiary": "#303030",
        "on-secondary-fixed": "#1b1c1c",
        "on-primary": "#2f3130",
        "background": "#131313",
        "on-secondary": "#303031",
        "on-primary-container": "#636563",
        "outline-variant": "#444846",
        "surface-container-low": "#1c1b1b"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "1.5rem",
        "space-md": "1rem",
        "margin": "2rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "gutter-sm": "1rem",
        "margin-lg": "4rem",
        "margin-sm": "1rem",
        "gutter-lg": "2rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        sans: ["'Hanken Grotesk'", "sans-serif"],
        "headline-lg": ["'Hanken Grotesk'", "sans-serif"],
        "headline-md": ["'Hanken Grotesk'", "sans-serif"],
        "body-lg": ["'Hanken Grotesk'", "sans-serif"],
        "body-md": ["'Hanken Grotesk'", "sans-serif"],
        "mono-technical": ["'JetBrains Mono'", "monospace"],
        "display-xl-mobile": ["'Hanken Grotesk'", "sans-serif"],
        "mono-micro": ["'JetBrains Mono'", "monospace"],
        "display-xl": ["'Hanken Grotesk'", "sans-serif"],
        "headline-lg-mobile": ["'Hanken Grotesk'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"]
      },
      fontSize: {
        "headline-lg": ["2.75rem", { lineHeight: "3rem", letterSpacing: "-0.03em", fontWeight: "400" }],
        "headline-md": ["1.5rem", { lineHeight: "1.875rem", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["0.9375rem", { lineHeight: "1.5rem", letterSpacing: "0em", fontWeight: "400" }],
        "mono-technical": ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "0.02em", fontWeight: "400" }],
        "display-xl-mobile": ["2.5rem", { lineHeight: "2.75rem", letterSpacing: "-0.03em", fontWeight: "400" }],
        "mono-micro": ["0.625rem", { lineHeight: "0.875rem", letterSpacing: "0.14em", fontWeight: "500" }],
        "display-xl": ["4.5rem", { lineHeight: "4.75rem", letterSpacing: "-0.04em", fontWeight: "400" }],
        "headline-lg-mobile": ["1.75rem", { lineHeight: "2.125rem", letterSpacing: "-0.02em", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
